title: 3rd Symposium on NLP for Social Good (NSG)
description:  2025
timezone: United Kingdom/Liverpool

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Accepted Papers: "/papers"
  Speakers: "/speakers"
  Programme: "/schedule"
  Organizers: "/organizers"
  Past Events: "/past"
show_downloads: false
