title: 2nd Symposium on NLP for Social Good (NSG)
description: 25th-26th April, 2024
timezone: United Kingdom/Liverpool

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Accepted Papers: "/papers"
  Speakers: "/speakers"
  Programme: "/schedule"
  Organizers: "/organizers"
  Past Events: "/past"
show_downloads: false
