title: 3rd Symposium on NLP for Social Good (NSG)
description:  2025
timezone: United Kingdom/Liverpool

navigation:
  Home: "/NSG"
  Call for Papers: "cfp.html"
  Accepted Papers: "papers.html"
  Speakers: "speakers.html"
  Programme: "programme.html"
  Organizers: "organizers.html"
  Past Events: "past.html"
show_downloads: false
